fix weird issue with some android images
turned the cert install steps into a more condensed thing.

diff --git a/burp-cert-to-android b/burp-cert-to-android
--- a/burp-cert-to-android
+++ b/burp-cert-to-android
@@ -30,9 +30,9 @@ convertCert() {
         echo "${RED}Cert file must be of type DER!${NC}"
         exit
     fi
-    openssl x509 -inform DER -in $burpCA -out cacert.pem
-    echo $(openssl x509 -inform PEM -subject_hash_old -in cacert.pem | head -1).0
-    mv cacert.pem $(openssl x509 -inform PEM -subject_hash_old -in cacert.pem | head -1).0
+    openssl x509 -inform DER -in $burpCA -out ./cacert.pem
+    androidCA=$(openssl x509 -inform PEM -subject_hash_old -in cacert.pem | head -1).0
+    mv ./cacert.pem $(openssl x509 -inform PEM -subject_hash_old -in cacert.pem | head -1).0
 }
 
 startEmulator() {
@@ -71,10 +71,14 @@ getEmulatorAPIVersion() {
 
 moveCertToEmulator() {
     adb root
-    adb remount
-    adb push $certName /sdcard/
-    adb shell mv /sdcard/$certName /system/etc/security/cacerts/
-    adb shell chmod 644 /system/etc/security/cacerts/$certName 
+    # I know this is ugly, but some AndroidImages will remount for only a few seconds.
+    # If any of these fail then the return status should let us know.
+    adb remount && adb push $androidCA /system/etc/security/cacerts/ && adb shell chmod 644 /system/etc/security/cacerts/$androidCA
+    if [ $? -eq 1 ]
+    then
+       echo "Failed to install certificate."
+       exit 1;
+    fi
     adb reboot
     echo -e "${GREEN}Certificate Successfully Installed!${NC}"
 }
@@ -87,4 +91,4 @@ if [ ! -f "$certName" ]; then
     exit
 fi
 startEmulator
-moveCertToEmulator "$certName"
+moveCertToEmulator
